Output demo/json-min.gif

Set Shell "bash"
Set FontSize 16
Set Padding 2
Set Margin 2
Set Width 1280
Set Height 1024
Set Framerate 60
Set TypingSpeed 150ms
Set PlaybackSpeed 0.5
Set CursorBlink false

Require go
Type "go run ." Enter

Sleep 3
Ctrl + h
Sleep 3

Ctrl + f

Enter
Backspace 9
Copy "api.coinlore.net"
Paste
Enter
Copy "/api/tickers/"
Paste
Enter 9
Space
Sleep 3
Ctrl + g
PageDown 10
Sleep 3
PageUp  10
Sleep 3
Ctrl + q
