name: vhs

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: charmbracelet/vhs-action@v1
        with:
          path: "demo/main.tape"
      - uses: charmbracelet/vhs-action@v1
        with:
          path: "demo/load-session.tape"
      - uses: charmbracelet/vhs-action@v1
        with:
          path: "demo/json-min.tape"

      - uses: devicons/public-upload-to-imgur@v2.2.2
        id: imgur_step
        with:
          path: demo/*.gif
          client_id: ${{ secrets.IMGUR_CLIENT_ID }}
